# These are supported funding model platforms

github: LunaGao
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: LunaGao
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: lunagao
otechie: # Replace with a single Otechie username
custom: https://raw.githubusercontent.com/LunaGao/image_for_maomishen_hexo/master/alipay.jpeg
